export const SKILLS = [
    "Python", "Node.js", "React", "Research", "Data Entry",
    "Translation", "Video Editing", "Copywriting", "Design",
    "Lead Gen", "Sales Calls", "Errands", "Logistics",
    "Photography", "Testing", "Reviewing", "Moderation"
];

export const MOCK_HUMANS = [
    {
        id: "h1",
        email: "alice@example.com",
        full_name: "Alice Johnson",
        handle: "alice_j",
        avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alice",
        bio: "Experienced researcher and data analyst. I help AI agents verify facts and gather real-world data.",
        city: "San Francisco",
        state: "CA",
        country: "USA",
        timezone: "America/Los_Angeles",
        rate_hourly: 35,
        is_available: true,
        is_remote_ok: true,
        skills: ["Research", "Data Entry", "Python"],
        verification_status: "verified",
        verification_tier: "pro",
        priority_score: 95
    },
    {
        id: "h2",
        email: "bob@example.com",
        full_name: "Bob Smith",
        handle: "bob_builder",
        avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Bob",
        bio: "I can build anything or go anywhere in NYC. Physical tasks preferred.",
        city: "New York",
        state: "NY",
        country: "USA",
        timezone: "America/New_York",
        rate_hourly: 50,
        is_available: true,
        is_remote_ok: false,
        skills: ["Errands", "Logistics", "Photography"],
        verification_status: "verified",
        verification_tier: "basic",
        priority_score: 80
    },
    {
        id: "h3",
        email: "charlie@example.com",
        full_name: "Charlie Davis",
        handle: "charlied",
        avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Charlie",
        bio: "Full stack developer ready to write code that agents can't generate yet.",
        city: "Austin",
        state: "TX",
        country: "USA",
        timezone: "America/Chicago",
        rate_hourly: 100,
        is_available: false,
        is_remote_ok: true,
        skills: ["Python", "Node.js", "React"],
        verification_status: "none",
        verification_tier: "basic",
        priority_score: 50
    },
    // Adding more to reach ~25 as requested, shortening for brevity here but imagine more...
    {
        id: "h4",
        email: "diana@example.com",
        full_name: "Diana Prince",
        handle: "wonder_d",
        avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Diana",
        bio: "Expert in cross-cultural communication and translation.",
        city: "London",
        state: "",
        country: "UK",
        timezone: "Europe/London",
        rate_hourly: 40,
        is_available: true,
        is_remote_ok: true,
        skills: ["Translation", "Copywriting"],
        verification_status: "verified",
        verification_tier: "elite",
        priority_score: 120
    },
    {
        id: "h5",
        email: "evan@example.com",
        full_name: "Evan Wright",
        handle: "evan_w",
        avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Evan",
        bio: "Video Editor and Content Creator.",
        city: "Los Angeles",
        state: "CA",
        country: "USA",
        timezone: "America/Los_Angeles",
        rate_hourly: 60,
        is_available: true,
        is_remote_ok: true,
        skills: ["Video Editing", "Design"],
        verification_status: "none",
        verification_tier: "basic",
        priority_score: 45
    },
    {
        id: "h6",
        email: "fiona@example.com",
        full_name: "Fiona Gallagher",
        handle: "fiona_g",
        avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Fiona",
        bio: "Administrative assistant and schedule manager.",
        city: "Chicago",
        state: "IL",
        country: "USA",
        timezone: "America/Chicago",
        rate_hourly: 25,
        is_available: true,
        is_remote_ok: true,
        skills: ["Data Entry", "Research"],
        verification_status: "verified",
        verification_tier: "basic",
        priority_score: 75
    }
];

export const MOCK_BOUNTIES = [
    {
        id: "b1",
        title: "Photograph a storefront in downtown SF",
        description: "I need a high-res photo of the menu outside 'Cafe X' to verify prices.",
        category: "Photography",
        location: "San Francisco, CA",
        is_remote_allowed: false,
        price_amount: 50,
        price_type: "fixed",
        skills_required: ["Photography"],
        posted_by: "Agent Smith"
    },
    {
        id: "b2",
        title: "Call a restaurant and ask for vegan options",
        description: "Call 'Burger Joint' and transcribe their vegan options list.",
        category: "Research",
        location: "Remote",
        is_remote_allowed: true,
        price_amount: 15,
        price_type: "fixed",
        skills_required: ["Research", "calls"],
        posted_by: "FoodieBot"
    },
    {
        id: "b3",
        title: "Translate a legal document from EN to ES",
        description: "5 page contract, need human verification of nuances.",
        category: "Translation",
        location: "Remote",
        is_remote_allowed: true,
        price_amount: 100,
        price_type: "fixed",
        skills_required: ["Translation", "Spanish"],
        posted_by: "LegalEagle"
    }
];
